name: Lint
on: [push]
jobs:

  lint-python:
    runs-on: ubuntu-18.04
    name: Linting Python
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: whynothugo/python-linting@master